# Generated by Django 3.1.5 on 2021-01-17 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_content', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('caption', models.CharField(blank=True, max_length=256)),
                ('gps_tag', models.CharField(blank=True, max_length=128)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('visibility', models.IntegerField(choices=[(0, 'Visible'), (1, 'Hidden')], default=0)),
                ('media_id', models.UUIDField()),
            ],
        ),
    ]
