# Generated by Django 3.1.7 on 2021-03-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('posts', '0002_auto_20210327_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_post', to='tags.Tag'),
        ),
    ]
