# Generated by Django 3.1.7 on 2021-03-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210202_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gps_tag',
        ),
        migrations.AddField(
            model_name='post',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
