# Generated by Django 3.1.7 on 2021-03-26 15:34

from django.db import migrations
import imagekit.models.fields
import users.models
import users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Profile Cover Picture', storage=users.storage.OverwriteStorage(), upload_to=users.models.profile_cover_image_upload_path, verbose_name='Profile Cover Picture'),
        ),
    ]
