# Generated by Django 3.1.7 on 2021-03-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Total points achieved by user'),
        ),
    ]
