# Generated by Django 3.1.7 on 2021-03-29 08:23

from django.db import migrations
import imagekit.models.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Profile Cover Picture', upload_to=users.models.profile_cover_image_upload_path, verbose_name='Profile Cover Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Profile Picture', upload_to=users.models.profile_image_upload_path, verbose_name='Profile Picture'),
        ),
    ]
