# Generated by Django 3.1.7 on 2021-03-27 00:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import game.models
import upload_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover Image', upload_to=game.models.Channel.coverimage_upload_path, validators=[upload_validator.FileTypeValidator(allowed_types=['image/png', 'image/jpeg', 'image/bmp', 'image/heic', 'image/heif', 'image/tiff', 'image/gif']), django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp', 'heic', 'heif', 'tiff', 'gif'])], verbose_name='Cover Image')),
                ('avatar', models.ImageField(blank=True, help_text='Channel Avatar', upload_to=game.models.Channel.avatar_upload_path, validators=[upload_validator.FileTypeValidator(allowed_types=['image/png', 'image/jpeg', 'image/bmp', 'image/heic', 'image/heif', 'image/tiff', 'image/gif']), django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp', 'heic', 'heif', 'tiff', 'gif'])], verbose_name='Channel Avatar')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Game Image', upload_to=game.models.Game.gameimage_upload_path, validators=[upload_validator.FileTypeValidator(allowed_types=['image/png', 'image/jpeg', 'image/bmp', 'image/heic', 'image/heif', 'image/tiff', 'image/gif']), django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp', 'heic', 'heif', 'tiff', 'gif'])], verbose_name='Game Image')),
                ('pinColorHex', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Leaderboard',
                'verbose_name_plural': 'Leaderboards',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.leaderboard')),
            ],
            options={
                'verbose_name': 'LeaderboardRow',
                'verbose_name_plural': 'LeaderboardRows',
            },
        ),
    ]
