# Generated by Django 3.1.7 on 2021-03-23 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('game', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.channel'),
        ),
        migrations.AddField(
            model_name='game',
            name='leaderboard',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='game.leaderboard'),
        ),
        migrations.AddField(
            model_name='game',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='in_game', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='channel',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed', to='users.Profile'),
        ),
    ]
