# Generated by Django 3.1.7 on 2021-03-27 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_tags'),
        ('game', '0003_auto_20210327_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatePost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.channel')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'verbose_name': 'ValidatePost',
                'verbose_name_plural': 'ValidatePosts',
                'ordering': ['timestamp'],
                'unique_together': {('game', 'post')},
            },
        ),
    ]
