# Generated by Django 3.1.7 on 2021-03-30 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210329_1543'),
        ('game', '0003_auto_20210329_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='chatroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_chatroom', to='chat.chatroom'),
        ),
    ]
