# Generated by Django 3.1.7 on 2021-03-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('game', '0004_channel_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_to_game', to='users.Profile'),
        ),
    ]
