# Generated by Django 3.1.7 on 2021-03-26 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210326_2219'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('name', 'channel')},
        ),
    ]
