# Generated by Django 3.1.7 on 2021-04-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('game', '0005_game_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='moderators',
            field=models.ManyToManyField(related_name='moderater', to='users.Profile'),
        ),
    ]
