# Generated by Django 3.1.7 on 2021-04-04 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210329_1543'),
        ('users', '0001_initial'),
        ('game', '0006_channel_moderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatepost',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.channel'),
        ),
        migrations.AlterField(
            model_name='validatepost',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AlterUniqueTogether(
            name='validatepost',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ReportedPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.channel')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_post', to='posts.post')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name': 'ReportedPost',
                'verbose_name_plural': 'ReportedPosts',
                'ordering': ['timestamp'],
                'unique_together': {('game', 'post')},
            },
        ),
    ]
